FROM python:3

RUN pip install elasticsearch
RUN pip install requests
RUN pip install simplejson
RUN pip install schedule
RUN pip install python-time
RUN pip install datetime
RUN pip install schedule
RUN pip install time